language: node_js

node_js:
  - 8
  - 6

before_script:
  - npm run lint
  - npm run build

after_success:
  - npm run codecov

stages:
  - name: test
  - name: release
    if: branch = master AND NOT type = pull_request AND repo = webnicer/d3actor

jobs:
  include:
    - stage: release
      node_js: 8
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
